### ISSUE TITLE
Rendering check for MemberExpression

### ISSUE THREAD

**Issue by fengberd** [mck89/peast#17]
* Peast Version: [461fbe9](https://github.com/mck89/peast/commit/461fbe96212ac1b511f527fd11b942e976429398)
* Issue: When rendering MemberExpression with `computed = false`, the renderer won't check if property is a legal Identifier
* Reproduce:
1. Parse the following code
```JavaScript
a[233] = false;
b['xx-dd'] = true;
```
2. Traverse the AST and execute `$node->setComputed(false);`
3. Render the script
4. The render result can be
```JavaScript
a.233 = false;
b.xx-dd = true;
```
Which is illegal and will cause syntax error.

**Comment by mck89** [comment]
I see the problem here but the solution can be problematic and MemberExpression is not the only case where this can happen so i have to collect all the cases.

I think there are 3 solutions for this:

- Ignore `setComputed(false)` if the property is not an identifier
- Raise an exception if `setComputed(false)` is called and the property is not an identifier
- Don't trust the `computed` flag in the Renderer and always use the square brackets syntax when the property is not an identifier

I'll take a look at it, thank you for reporting.

**Comment by fengberd** [comment]
Fine, I managed to solve this problem by the following checks, however, most unicode characters can be legal identifier, so the following regex isn't perfect for identifier check.
```PHP
// TODO: PCRE doesn't recognize \xA0-\x{FFFF}...
$legal = node_type($node->getProperty(), 'StringLiteral') && preg_match('/^[_$a-zA-Z][_$a-zA-Z0-9]*$/', val($node->getProperty()));
$node->setComputed(!$legal);
// You may ignore the following code, it's used to solve expressions like (233).toFixed();
if($legal)
{
	$node->setProperty((new Identifier)->setName($node->getProperty()->getValue()));
	if(node_type($node->getObject(), 'NumericLiteral'))
	{
		$node->setObject((new ParenthesizedExpression)->setExpression($node->getObject()));
	}
}
```
Hope this helps, thanks for your reply :D

**Comment by mck89** [comment]
I've done some tests and find out that it was necessary only on member expressions. I've just released a new version that includes the fix for this bug.

**Comment by fengberd** [comment]
Thanks.
