### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by EricPoggel** [mck89/peast#28]
Would it be feasible to add TypeScript support?

Then it'd be easy for me convert typescript to javascript by walking the AST and omitting the typescript only features.

This could be used with a .htaccess rewrite to convert typescript to javascript on the fly, allowing for:

<script src="main.ts"></script>

The http request to main.ts would return the transpiled javascript.

That script could cache the generated .js files.  On a new request they would only be generated if the .ts file was newer than the generated .js file.

I think this could become a very popular and easy way to serve JavaScript from TypeScript on any web server with php, allowing developers to skip complicated node.js build configurations.

**Comment by mck89** [comment]
Actually i've tought about it in the past, but there are 2 main problems:

1. There is no documentation about how TypeScript syntax integrates with EcmaScript syntax and that makes the development process really hard. I found [this documentation](https://github.com/microsoft/TypeScript/blob/master/doc/spec-ARCHIVED.md) that is exactly what is needed but it's not mantained anymore and it's outdated.
2. Estree does not provide interfaces for TypeScript syntax and that's another big problem since it could save a lot of headhaches in the definition of an abstract syntax tree

I didn't want to implement JSX too but, when it was requested in another issue, i saw that there was all the necessary documentation to proceed, so i had not excuses. Another big difference is that JSX implements only one new syntax, while TS is a lot more complicated and it's really a big amount of work for one person.

I close the issue for now, but i will revaluate it if some documentation will come out.

**Comment by tyrann0us** [comment]
Hi @mck89, just following up on this one. Has something changed in the two years since you closed this issue? Is TypeScript support something you'd consider adding now?

Allow me to give you some context:
In WordPress, the so-called "[block editor](https://wordpress.org/support/article/wordpress-editor/)" is written in React and more and more developers use TypeScript (`.tsx`) to develop React components and blocks for it.
Now, there are translation functions (refer [here](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-react-i18n/) for details, PHP counterpart details [here](https://developer.wordpress.org/themes/functionality/internationalization/)) that allow you to translate strings in your components. For this, all these strings must be "extracted" from the source code. For the WordPress context, there exists a tool called [GlotPress](https://github.com/GlotPress/GlotPress) that provides a translation UI. The actual string extraction is done by [Traduttore](https://github.com/wearerequired/traduttore), which in turn uses the official WordPress CLI ([WP-CLI](https://wp-cli.org/)) to parse the source code.

And here's where it's getting interesting: WP-CLI's string extraction command ([`wp i18n make-pot`](https://developer.wordpress.org/cli/commands/i18n/make-pot/)) uses your great library to parse JS files. But since it doesn't support TypeScript, developers are not able to extract translatable strings from their source code if they use TypeScript.

Please see this issue for details: https://github.com/wp-cli/i18n-command/issues/176

**Comment by tyrann0us** [comment]
Hi @mck89, admittedly, I don’t know anything about language parsers and ASTs.
However, from a quick Google search it looks like https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/typescript-estree is a npm-based TypeScript parser. Could this theoretically act as a source for TypeScript support in Peast? Basically porting it to a PHP version?
Thanks!
