### ISSUE TITLE
Comment rendering

### ISSUE THREAD

**Issue by dudecacholinha** [mck89/peast#36]
Hello, I have been using this library and it works like a charm, my only problem is that I can´t force the rendering of comments. I have been searching through the classes and found that the Base renderer has an attribute called $renderComments, but I don´t know how to use it or even if it can be used.

I have tried the following but with no luck :
<img width="557" alt="image" src="https://user-images.githubusercontent.com/28741496/119835972-3f1e0c00-bef9-11eb-8508-ee18f6cf352a.png">

Any help is appreciated
Duarte Guerreiro

**Comment by mck89** [comment]
There's no way right now to render comments.
That property is there since i first wrote the Renderer class but it's never used, i've tried a couple times to implement comments rendering but it's very hard since in many cases it broke the generated code.
However, it's always on my todo list and as soon as I have time I will try to work on it again.

**Comment by dudecacholinha** [comment]
Ok that's what I thought thanks for answering anyway, I will close the issue
