### ISSUE TITLE
Cannot parse newline in string argument

### ISSUE THREAD

**Issue by swissspidy** [mck89/peast#41]
The following code cannot be parsed with Peast:

```js
throw new TypeError("Hello\nWorld")
```

While this works:

```js
throw new TypeError("Hello World")
```

Getting the following error:

```
Peast\Syntax\Exception: Unterminated string
```

AST for the above code:

```json
{
  "type": "Program",
  "start": 0,
  "end": 35,
  "body": [
    {
      "type": "ThrowStatement",
      "start": 0,
      "end": 35,
      "argument": {
        "type": "NewExpression",
        "start": 6,
        "end": 35,
        "callee": {
          "type": "Identifier",
          "start": 10,
          "end": 19,
          "name": "TypeError"
        },
        "arguments": [
          {
            "type": "Literal",
            "start": 20,
            "end": 34,
            "value": "Hello\nWorld",
            "raw": "\"Hello\\nWorld\""
          }
        ]
      }
    }
  ],
  "sourceType": "module"
}
```

**Comment by mck89** [comment]
Sorry but i can't reproduce it, are you sure you are escaping that "\n" so that it's not parsed by php itself? The "Unterminated string" is correct if there's a new line inside a string.

Also in this way i get the same error you reported:
`\Peast\Peast::latest("throw new TypeError(\"Hello\nWorld\")")->parse()`

In this way it works:
`\Peast\Peast::latest("throw new TypeError(\"Hello\\nWorld\")")->parse()`

**Comment by swissspidy** [comment]
You're right, I just tested this again by loading the whole JS from a file instead of a string and it works just fine.

Sorry about that!
