### ISSUE TITLE
Customize the grammar a bit?

### ISSUE THREAD

**Issue by frodeborli** [mck89/peast#52]
Hi, awesome project - I will be looking into it.

I would actually like to parse a toy programming language similar to JavaScript for fun; but for that I would need to extend your parser with a few new keywords.

What would be the proper approach if I wanted:

1. Typed variables; instead of "const", "let" and "var" I want "bool" etc.
2. New method modifier keywords (public, protected, private)

I don’t want to fork your parser; I want to extend it ideally. This toy language is a subset of JavaScript, and I would just validate the AST instead of modifying the parser too much.

**Comment by mck89** [comment]
Well i think you can extend the parser and then overwrite the methods that parse specific grammars that you want to change, for example replacing the method that parses "const", "let" and "var" to add your own syntax.

That's the way the parser initially handled multiple ECMA versions, the base parser was the ES6 one, then the ES7 parser extended the ES6 and replaced the grammar that have changed between those versions.

BUT you will have hard times mantaining the project in this way. You should check all the releases and make sure that no logic have been introducted in those methods and i can't guarantee that the internal api won't change. This parsers is not designed to be extended with additional syntax, you should really consider to use some more generic parser like [PHP-Yacc](https://github.com/ircmaxell/PHP-Yacc) for example, this will take more time to start because you have write the parsing rules by yourself, but it will save you a lot of time in the future.
