### ISSUE TITLE
Fatal error when xdebug enabled

### ISSUE THREAD

**Issue by bart-jaskulski** [mck89/peast#53]
Not really a bug, but I thought it would be worth to mention.

Runinng `peast` parser with `php` with enabled `xdebug` may lead to fatal error, as xdebug thinks we are inside infinite loop and exit the process forcefully.

It happens to me when I parse files with `wp i18n` command and my environment happens to have xdebug enabled by default.

Simply prefixing called command with env `XDEBUG_MODE=off` works around that issue.

**Comment by mck89** [comment]
Can you tell me which error do you get?

**Comment by bart-jaskulski** [comment]
https://gist.github.com/bart-jaskulski/ed8fcf875b3b634db1f2c741cc22ba12

That's the whole error trace. There are two errors thrown along the way, but what matters is on line [269](https://gist.github.com/bart-jaskulski/ed8fcf875b3b634db1f2c741cc22ba12#file-error-log-L269) and [541](https://gist.github.com/bart-jaskulski/ed8fcf875b3b634db1f2c741cc22ba12#file-error-log-L541)

**Comment by mck89** [comment]
Ok that's what i thought, i've seen the same issue here: 
https://github.com/wp-cli/i18n-command/issues/80

So i've added a Known Issues section in the readme file proposing their solution to the problem, it's just the `xdebug.max_nesting_level` setting that need to be set to a higher value, such as 512 instead of 256.

The other error in your backtrace is: PHP Fatal error:  __debuginfo() must return an array

But i think it's due to the Xdebug error handling since i'm not using __debuginfo at all in this project.

I'll close this issue since there's nothing i can do about this errors unfortunately, thank you for reporting the problem!
