### ISSUE TITLE
wp i18n make-pot (WordPress) failing to parse specific JavaScript code

### ISSUE THREAD

**Issue by markhowellsmead** [mck89/peast#54]
**Describe the current, buggy behavior**

When running `wp i18n make-pot . languages/shp_gantrisch_adb.pot` on the command line in a site shell from the Local app on Mac OSX, a very long error message is generated. The initial message is `Warning: Uncaught Error in exception handling during call to Error::__toString() in phar:///Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cli.phar/vendor/mck89/peast/lib/Peast/Syntax/Scanner.php on line 0`

**Describe how other contributors can replicate this bug**
Run  `wp i18n make-pot . languages/shp_gantrisch_adb.pot` on the command line in a site shell from the Local app on Mac OSX.

**Describe what you would expect as the correct outcome**

The POT file be generated without any error messages.

**Let us know what environment you are running this on**

```
OS:	Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/Users/mark/Library/Application Support/Local/lightning-services/php-8.0.22+5/bin/darwin/bin/php
PHP version:	8.0.22
php.ini used:	/Users/mark/Library/Application Support/Local/run/_qwoyVNya/conf/php/php.ini
MySQL binary:	/Applications/Local.app/Contents/Resources/extraResources/lightning-services/mysql-8.0.16+6/bin/darwin/bin/mysql
MySQL version:	mysql  Ver 8.0.16 for macos10.14 on x86_64 (MySQL Community Server - GPL)
SQL modes:	ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/mark/Projects/fse/app/public/wp-content/plugins/shp_gantrisch_adb
WP-CLI packages dir:	
WP-CLI global config:	/Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/config.yaml
WP-CLI project config:	
WP-CLI version:	2.6.0
```

**Comment by markhowellsmead** [comment]
See also https://github.com/wp-cli/i18n-command/issues/347

**Comment by mck89** [comment]
I don't think that's a Peast bug, i've just run the code you attached and it works without any error.
I really can't help you with this, maybe is just something related to the wp-cli command, i don't know.

That error `Warning: Uncaught Error in exception handling during call to Error::__toString()` seems to be something that is hiding the real error, but again i can't replicate it so i have no clues.

Maybe you can try to run Peast directly on that source code and see if it works, if it's ok than this is something related to wp-cli otherwise you will see the real error that will be very helpful.
