### ISSUE TITLE
Utils::quoteLiteralString escapes \uFFF characters

### ISSUE THREAD

**Issue by Domi04151309** [mck89/peast#57]
When setting a new value to a `StringLiteral` using the [`setValue` ](https://github.com/mck89/peast/blob/cf06286910b7efc9dce7503553ebee314df3d3d3/lib/Peast/Syntax/Node/StringLiteral.php#L59)method all unicode escapes are escaped again in [`Utils::quoteLiteralString`](https://github.com/mck89/peast/blob/cf06286910b7efc9dce7503553ebee314df3d3d3/lib/Peast/Syntax/Utils.php#L220).

Example:

`\u0076\u0061\u0072\u0069\u0061\u0062\u006c\u0065\u0073` turns into `\\u0076\\u0061\\u0072\\u0069\\u0061\\u0062\\u006c\\u0065\\u0073`

**Comment by mck89** [comment]
That's how it should work, `setValue` makes sure it stores exactly the value you pass in, so it applies all the required escaping.
Right now the only way to add a unicode escaped sequence is to use the `setRaw` method like this:

```
$str->setRaw("'\u0076\u0061\u0072\u0069\u0061\u0062\u006c\u0065\u0073'");
```

It takes the exact string representation so the value should be surrounded by quotes.

That's ugly, i know, but i'll try to think about a better handling for the next releases.

**Comment by Domi04151309** [comment]
Thanks for the quick reply. The `setRaw` method works well. Since I do not have enough expertise here I was wondering why the input would have to be escaped in the first place. I realized this behavior after using the renderer where the result did show the characters with double slashes.

**Comment by mck89** [comment]
I think that escaping the input is the right behaviour for the `setValue` method because it guarantees that what you pass to the method is exactly what you will get in the string when you will render it. Handling of unicode escaped sequence is the only downside of this behaviuour, maybe adding a `setRawValue` method with the benefits of `setRaw` but without the need of surrounding quotes can be the right solution, i will evalutate it for a future release.
