### ISSUE TITLE
Cannot parse dynamic import

### ISSUE THREAD

**Issue by michaelzangl** [mck89/peast#7]
The parser does not support dynamic import expressions (e.g. used by webpack)

```js
import('some-file.js').then(_ => {})
```

Workaround: Before parsing the file, substitute all `import\s+(` strings with an alternative token, it will then be exposed as function call in the AST.

**Comment by mck89** [comment]
As you can see [here](https://github.com/tc39/proposals) dynamic import is still a proposal, it's not in the official ECMAScript specification yet and that's why it's not supported at the moment. I know some browsers already implement it, but i want this project to be conformant to the specs since proposals can change at any time until they get included.

**Comment by ockham** [comment]
It appears that dynamic `import()`s [reached Stage 4 in June](https://github.com/tc39/tc39-notes/blob/master/meetings/2019-06/june-4.md#dynamic-import-for-stage-4). Is it time to re-open this issue? :slightly_smiling_face:

**Comment by mck89** [comment]
Yes the time has come 🙂. Anyway i will keep this issue as a reminder to implement all the new features, not only to dynamic import, just need to find the time to do it.

**Comment by mck89** [comment]
I've released a new version that contains the 2020 parser with support for dynamic import and BigInt
